version: '3.8'

services:
 
  frontend:
    build: ./task-flow-frontend       
    container_name: taskflow_frontend
    ports:
      - "80:80"              
    depends_on:
      - backend


  backend:
    build: ./TaskFlowManager       
    container_name: taskflow_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/taskflow_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

    ports:
      - "8080:8080" 

  db:
    image: postgres:16-alpine
    container_name: taskflow_db_container
    environment:
      POSTGRES_DB: taskflow_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: